### ISSUE TITLE
Import for grid-pro is missing

### ISSUE THREAD

**Issue by monobyte** [genesiscommunitysuccess/blank-app-seed#35]
Package.json needs to include a reference to grid-pro or it includes the last main version, which might not be the same as the version of FUI specified in the project.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/128296/214657292-9eb91675-0be9-4f10-9419-499d8e7f2d99.png">

**Comment by cistov** [comment]
This should be fixed now that https://github.com/genesislcap/foundation-ui/pull/1010 has been merged.
